<template>
    <div class="document">
        <!-- eslint-disable -->
        <h3 align="center">
            Summarization Evaluation
        </h3>
        <p>You are being invited to take part in a research project. Before you decide whether or not to participate, <strong>it is important for you to understand why the research is being done and what it will involve</strong>.</p>
        <p>Please take time to read the following information carefully and discuss it with others if you wish. Ask us if there is anything that is not clear or if you would like more information. Take time to decide whether or not you wish to take part. All information provided will be anonymous and will be used for academic purposes only.</p>
        <p>The task is to evaluate the <strong>fluency</strong> and <strong>clarity</strong> of a single sentence generated by a natural language generation system. The task should be possible to complete in less than <strong>3 minutes</strong>.</p>
        <hr/>
        <p><strong>Fluency</strong></p>
        <p>In determining the fluency, you need to look for any obvious ungrammatical parts, e.g., missing components, unrelated fragments, or any other grammar-related problem that makes the text difficult to read.</p>
        <p><strong>Sentence that isn’t fluent (grammatical error, does not sound natural):</strong></p>
        <blockquote><em>
            “Officials from IAEA and the european conventions were suspected by experts of an enrichment effort to obtain technologies used to obtain technologies that would be used for tehran in tehran and if the issue is considered the IAEA and the european conventions to produce the atomic bomb .”</em></blockquote>

        <p><strong>Sentences that is fluent:</strong></p>
        <blockquote><em>“China and Kyrgyzstan pledge to make joint efforts to crack down on terrorism and other threats to regional and global security”</em></blockquote>

        <p>You will be scoring each sentence by stating how strongly you agree or disagree using a slider from scale 1 (strong disagreement) to 100 (strong agreement) based on how fluent the sentence is to the reader (grammatically correct, natural sounding). All sentences are generated by summarising newswire articles and should not be upsetting to the reader.</p>

        <hr />
        <p><strong>Clarity</strong></p>
        <p>In determining the clarity, you need to look for any difficulty in identifying the referents of noun phrases in the summary, e.g. nouns, pronouns or personal names that are not well-specified, or any other entity that is referenced but its identity and relation with the story remains unclear.</p>
        <p><strong>Sentence that isn’t clear (it is not clear who is the woman and which truck, the context is also not clear):</strong></p>
        <blockquote><em>
            “The woman had been riding in the truck when she started to grow increasingly uneasy with the man.”</em></blockquote>

        <p><strong>Sentences that is clear:</strong></p>
        <blockquote><em>“Juan David Ortiz, a 35-year-old supervisory Border Patrol agent, has been charged with four counts of murder,”</em></blockquote>

        <p>You will be scoring each sentence by stating how strongly you agree or disagree using a slider from scale 1 (strong disagreement) to 100 (strong agreement) based on how clear the sentence is to the reader. All sentences are generated by summarising newswire articles and should not be upsetting to the reader.</p>

        <hr/>
        <p>It is up to you to decide whether or not to take part. If you do decide to take part you will be asked to click a consent button at the end of this section, of which you can still withdraw at any time before we processed the data (3 days after the closing date) without any consequences.</p>
        <p>You do not have to give a reason. If you wish to withdraw from this research, please contact <a href="mailto:hhardy2@sheffield.ac.uk">the organizer</a></p>

        <p>All the information that we collect about you during the course of the research will be kept strictly confidential and will only be accessible to members of the research team. It will not be possible to be identified in any reports or publications unless you have given us your explicit consent for this. We will not share any of your information to other parties.</p>

        <p>According to data protection legislation, we are required to inform you that the legal basis we are applying in order to process your personal data is that ‘processing is necessary for the performance of a task carried out in the public interest’ (Article 6(1)(e)).</p>
        <p>Further information can be found in the <a target="_blank" href="https://www.sheffield.ac.uk/govern/data-protection/privacy/general.">University’s Privacy Notice</a>
        </p>

        <p>Thank you for reading this</p>

        <p>
Contact details of organizer:<br/><br/>

Hardy<br/>
PhD Student<br/>
The University of Sheffield<br/>
hhardy2@sheffield.ac.uk<br/>
        </p>

        <p>
            Do you consent for this information to be used
            anonymously for research purposes only?
        </p>
        <!-- eslint-enable -->
    </div>
</template>

<script>
export default {
  name: 'LandingFluency',
};
</script>
<style scoped lang="scss">
h3 {
    margin-top: 2rem;
    margin-bottom: 3rem;
}
.document {
  font-family: 'Lora', serif;
  font-size: 1.1rem;
  line-height: 1.5rem;
  padding-left: 2rem;
  padding-right: 2rem;
  padding-bottom: 2rem;
}
</style>
