"""empty message

Revision ID: b63d6bed5217
Revises: 
Create Date: 2019-07-26 12:13:24.940666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63d6bed5217'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('annotation_project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doc_id', sa.String(length=25), nullable=False),
    sa.Column('doc_json', sa.Text(), nullable=False),
    sa.Column('sanity_statement', sa.Text(), nullable=True),
    sa.Column('sanity_answer', sa.Boolean(), nullable=True),
    sa.Column('sanity_statement_2', sa.Text(), nullable=True),
    sa.Column('sanity_answer_2', sa.Boolean(), nullable=True),
    sa.Column('has_highlight', sa.Boolean(), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_ref', sa.Boolean(), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('total_exp_results', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('doc_id', sa.INTEGER(), nullable=False),
    sa.Column('proj_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['proj_id'], ['annotation_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('summ_group_id', sa.INTEGER(), nullable=False),
    sa.Column('highlight', sa.Boolean(), nullable=True),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['summ_group_id'], ['summary_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('summary_group_id', sa.INTEGER(), nullable=False),
    sa.Column('doc_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['summary_group_id'], ['summary_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('validity', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status_id', sa.INTEGER(), nullable=False),
    sa.Column('mturk_code', sa.String(length=255), nullable=True),
    sa.Column('is_filled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['doc_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summaries_pair',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ref_summary_id', sa.INTEGER(), nullable=False),
    sa.Column('system_summary_id', sa.INTEGER(), nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['ref_summary_id'], ['summary.id'], ),
    sa.ForeignKeyConstraint(['system_summary_id'], ['summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('total_exp_results', sa.Integer(), nullable=False),
    sa.Column('ref_summary_id', sa.INTEGER(), nullable=True),
    sa.Column('summary_id', sa.INTEGER(), nullable=False),
    sa.Column('proj_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['proj_id'], ['evaluation_project.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('precision', sa.REAL(), nullable=False),
    sa.Column('recall', sa.REAL(), nullable=False),
    sa.Column('fluency', sa.REAL(), nullable=False),
    sa.Column('clarity', sa.REAL(), nullable=False),
    sa.Column('validity', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('sliderMax', sa.INTEGER(), nullable=True),
    sa.Column('sliderMin', sa.INTEGER(), nullable=True),
    sa.Column('sliderValues', sa.String(length=255), nullable=True),
    sa.Column('status_id', sa.INTEGER(), nullable=False),
    sa.Column('mturk_code', sa.String(length=255), nullable=True),
    sa.Column('is_filled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['summary_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_result')
    op.drop_table('summary_status')
    op.drop_table('summaries_pair')
    op.drop_table('annotation_result')
    op.drop_table('summary')
    op.drop_table('evaluation_project')
    op.drop_table('doc_status')
    op.drop_table('summary_group')
    op.drop_table('document')
    op.drop_table('annotation_project')
    op.drop_table('user')
    op.drop_table('dataset')
    # ### end Alembic commands ###
